---
title: "hope this works"
date: 2021-03-10
---

title: Ayooo "We Out Here"
author: Gato
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  testing this seeing how it works
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
end test

# social links
twitter_username: rrryour-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  gato21oakland # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
